name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Dependencies
              run: npm run install

            - name: Build
              run: npm run build:app

            - name: Move Build Files
              run: |
                  mkdir gh-pages
                  mv ./dist/* ./gh-pages/

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  BRANCH: gh-pages
                  FOLDER: ./gh-pages
