name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Dependencies
              run: npm ci

            - name: Run Custom Install Script
              run: npm run install:app

            - name: Build
              run: npm run build:app

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  BRANCH: gh-pages
                  FOLDER: ./dist
